# Generated by Django 4.2.3 on 2023-10-10 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('domain_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('feed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sort_order', models.SmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partner')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.provider')),
            ],
            options={
                'verbose_name': 'Partner Provider(Kayak)',
                'verbose_name_plural': 'Partner Providers(Kayak)',
            },
        ),
    ]
