# Generated by Django 4.2.3 on 2023-11-30 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBrandLocationDefinedSetsRatio',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('brand_location_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('defined_set_name', models.CharField(blank=True, max_length=500, null=True)),
                ('ratio_group_data', models.JSONField(blank=True, editable=False, null=True)),
                ('ratio_set_data', models.JSONField(blank=True, editable=False, null=True)),
                ('ratio_set_title', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('predicted_ratio_title', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('property_group_name', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('device_name', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('location_name', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('brand_name', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('search_location_name', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('brand', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='brands.brand')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sts.device')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sts.location')),
                ('predicted_ratio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sts.predictedratio')),
                ('property_group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='property.propertygroup')),
                ('ratio_group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sts.ratiogroup')),
                ('ratio_set', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sts.ratioset')),
                ('search_location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sts.searchlocation')),
            ],
            options={
                'verbose_name': 'historical Brand Location Ratio Set',
                'verbose_name_plural': 'historical Brand Location Ratio Sets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
