# Generated by Django 4.2.3 on 2023-11-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sts', '0002_historicalbrandlocationdefinedsetsratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalbrandlocationdefinedsetsratio',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
