# Generated by Django 4.2.3 on 2024-01-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sts', '0003_alter_historicalbrandlocationdefinedsetsratio_history_change_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
