# Generated by Django 4.2.3 on 2024-02-02 10:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partner_id'),
        ('sts', '0007_alter_ratiogroup_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicatePropertyPartnerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bldsr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sts.brandlocationdefinedsetsratio')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partner')),
            ],
            options={
                'unique_together': {('partner', 'bldsr', 'order')},
            },
        ),
    ]
