# Generated by Django 4.2.3 on 2024-02-05 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partner_id'),
        ('sts', '0008_duplicatepropertypartnerorder'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='duplicatepropertypartnerorder',
            unique_together={('partner', 'bldsr')},
        ),
    ]
