# Generated by Django 4.2.3 on 2024-02-05 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sts', '0010_alter_duplicatepropertypartnerorder_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='duplicatepropertypartnerorder',
            unique_together=set(),
        ),
    ]
