# Generated by Django 4.2.3 on 2024-02-07 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partner_id'),
        ('sts', '0011_alter_duplicatepropertypartnerorder_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBehindPopUnderMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bldsr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sts.brandlocationdefinedsetsratio')),
                ('details_lb_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details_lb_partner', to='partners.partner')),
                ('popunder_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='popunder_partner', to='partners.partner')),
                ('tiles_lb_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiles_lb_partner', to='partners.partner')),
            ],
        ),
    ]
