# Generated by Django 4.2.3 on 2024-02-07 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_partnerpropertytype_id'),
        ('sts', '0013_leavebehindpopundermap_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebehindpopundermap',
            name='property_type',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='property.propertytype'),
            preserve_default=False,
        ),
    ]
