# Generated by Django 4.2.3 on 2024-02-07 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_partnerpropertytype_id'),
        ('partners', '0002_alter_partner_id'),
        ('sts', '0014_leavebehindpopundermap_property_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='leavebehindpopunderrules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_lb_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details_lb_partner', to='partners.partner')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sts.device')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sts.location')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partner')),
                ('popunder_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='popunder_partner', to='partners.partner')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.propertytype')),
                ('tiles_lb_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiles_lb_partner', to='partners.partner')),
            ],
            options={
                'verbose_name': 'LeaveBehind & PopUnder Rule',
                'verbose_name_plural': 'LeaveBehind & PopUnder Rules',
                'unique_together': {('location', 'partner', 'device', 'property_type')},
            },
        ),
        migrations.DeleteModel(
            name='LeaveBehindPopUnderMap',
        ),
    ]
