# Generated by Django 4.2.3 on 2024-02-08 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sts', '0015_leavebehindpopunderrules_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavebehindpopunderrules',
            options={'verbose_name': 'Leave Behind & PopUnder Rule', 'verbose_name_plural': 'Leave Behind & PopUnder Rules'},
        ),
    ]
