# Generated by Django 4.2.3 on 2024-02-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sts', '0017_alter_leavebehindpopunderrules_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leavebehindpopunderrules',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='leavebehindpopunderrules',
            name='property_type',
            field=models.CharField(choices=[('Rental', 'rental'), ('Hotel', 'hotel')], max_length=50),
        ),
    ]
