# Generated by Django 4.2.3 on 2024-02-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sts', '0018_alter_leavebehindpopunderrules_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebehindpopunderrules',
            name='property_type',
            field=models.CharField(choices=[('rental', 'Rental'), ('hotel', 'Hotel')], max_length=50),
        ),
    ]
