# Generated by Django 4.2.3 on 2024-01-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_propertycategory_id_alter_propertygroup_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerpropertytype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
