version: '3.8'
services:
  search-tweak:
    image: 234464546150.dkr.ecr.us-west-2.amazonaws.com/search-tweak:search-tweak-2021-06-24-10-38-40

    ports:
      - "80:8000"
    ulimits:
            nofile:
                soft: 65535
                hard: 65535

    container_name: search-tweak
    restart: unless-stopped