# Generated by Django 4.2.3 on 2024-01-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqs', '0005_alter_setlistes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteenablesetses',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
