version: "3.2"
services:
  sts-staging:
    image: 234464546150.dkr.ecr.us-west-2.amazonaws.com/sts:sts-re-brand-2021-06-24-10-38-40
    
    ports:
      - "9001:8000"
    env_file:
      - .env

    container_name: sts-staging
    restart: unless-stopped