# Generated by Django 4.2.3 on 2023-11-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VrsAnalytics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('device', models.CharField(blank=True, max_length=50, null=True)),
                ('user_source', models.CharField(blank=True, max_length=50, null=True)),
                ('medium', models.CharField(blank=True, max_length=100, null=True)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('activity_time', models.DateTimeField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, max_length=200, null=True)),
                ('referral_page', models.TextField(blank=True, null=True)),
                ('page_path', models.TextField(blank=True, null=True)),
                ('feed', models.IntegerField(blank=True, null=True)),
                ('partner_url', models.TextField(blank=True, null=True)),
                ('pagetype', models.CharField(blank=True, max_length=50, null=True)),
                ('revenue', models.FloatField(blank=True, null=True)),
                ('usd_rate', models.FloatField(blank=True, null=True)),
                ('partner_response', models.JSONField(blank=True, null=True)),
                ('google_client_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('revenue_usd', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=15, null=True)),
                ('continent', models.CharField(blank=True, max_length=50, null=True)),
                ('country_code', models.CharField(blank=True, max_length=30, null=True)),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('ad_id', models.TextField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('user_first_visit_date', models.DateField(blank=True, null=True)),
                ('property_info', models.JSONField(blank=True, null=True)),
                ('predicted_revenue', models.FloatField(blank=True, null=True)),
                ('property_id', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('pz_advertiser', models.TextField(blank=True, null=True)),
                ('pushed_to_ga', models.SmallIntegerField()),
                ('stay_probability', models.FloatField(blank=True, null=True)),
                ('pushed_refund_to_ga', models.SmallIntegerField()),
                ('slack_notified', models.BooleanField(blank=True, null=True)),
                ('updated_partner_response', models.JSONField(blank=True, null=True)),
                ('sale_amount', models.FloatField(blank=True, null=True)),
                ('campaign_name', models.CharField(blank=True, max_length=500, null=True)),
                ('keywords', models.CharField(blank=True, max_length=500, null=True)),
                ('brand_key', models.CharField(blank=True, max_length=50, null=True)),
                ('site_key', models.CharField(blank=True, max_length=50, null=True)),
                ('site_published_status', models.BooleanField(blank=True, null=True)),
                ('conversion_key', models.TextField(blank=True, null=True)),
                ('revenue_unadjusted', models.FloatField(blank=True, null=True)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('travel_purpose', models.CharField(blank=True, max_length=300, null=True)),
                ('pushed_to_ga4', models.SmallIntegerField()),
                ('pushed_refund_to_ga4', models.SmallIntegerField()),
                ('pushed_to_gads', models.CharField(max_length=7)),
                ('estimated_ml_revenue', models.FloatField(blank=True, null=True)),
                ('pushed_refund_to_gads', models.SmallIntegerField()),
                ('is_user_activity_sync', models.BooleanField()),
                ('payslip_id', models.CharField(blank=True, max_length=200, null=True)),
                ('partner', models.CharField(blank=True, max_length=50, null=True)),
                ('referral_partner_key', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'vrs_analytics',
                'managed': False,
            },
        ),
    ]
